apiVersion: apps/v1
kind : Deployment
metadata :
  name : instrumentation-deployment
  labels :
    app : instrumentation
  spec:
    replicas: 3
    selector : 
      matchLabels:
        app : instrumentation
    template:
      metadata:
        labels:
          app: instrumentation
      spec:
        containers:
          - name : instrumentation
            image : alex7285/instrumentation:latest
            ports:
            containerPort : 8080